<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Reems-MacBook-Air.local" failures="1" tests="7" name="scripts._12_Actions_Class" time="93.984" errors="0" timestamp="2022-06-11T14:42:46 CDT" skipped="0">
  <testcase classname="scripts._12_Actions_Class" name="moveToElementPractice1" time="12.028"/>
  <system-out/>
  <testcase classname="scripts._12_Actions_Class" name="moveToElementPractice2" time="32.047"/>
  <system-out/>
  <testcase classname="scripts._12_Actions_Class" name="clickOnElementPractice" time="7.856">
    <failure message="expected [https://www.techglobalschool.com/apply-now-1] but found [https://www.techglobalschool.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.techglobalschool.com/apply-now-1] but found [https://www.techglobalschool.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at scripts._12_Actions_Class.clickOnElementPractice(_12_Actions_Class.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </failure>
  </testcase> <!-- clickOnElementPractice -->
  <system-out/>
  <testcase classname="scripts._12_Actions_Class" name="rightClickPractice" time="8.463"/>
  <system-out/>
  <testcase classname="scripts._12_Actions_Class" name="clickHoldAndReleasePractice" time="10.035"/>
  <system-out/>
  <testcase classname="scripts._12_Actions_Class" name="sendKeysToAnElement" time="7.702"/>
  <system-out/>
  <testcase classname="scripts._12_Actions_Class" name="practiceKeyDownAndKeyUp" time="15.853"/>
  <system-out/>
</testsuite> <!-- scripts._12_Actions_Class -->
